version: '3.8'

services:
  db:
    image: mysql:8.0
    ports:
      - 5050:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 00bfc8c729f5d4d529a412b12c58ddd2
      MYSQL_DATABASE: Tryout
      MYSQL_PASSWORD: 00bfc8c729f5d4d529a412b12c58ddd2
volumes:
  db_data: {}