name: CI-deployment-solicitacao-tryout

on:
  push:
    branches:
      - main
jobs:
  checkout-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Protocol SCP server remote
        uses: appleboy/scp-action@master
        with:
          host: 185.209.179.253
          username: app
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "projetos/Mfs/solicitacao-tryout/back"
      - name: Deploy to Sever
        uses: appleboy/ssh-action@master
        with:
          host: 185.209.179.253
          username: app
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: cd /home/app/projetos/Mfs/solicitacao-tryout/ && docker-compose down && docker-compose up -d --build
