name: CI

on:
  pull_request:
    branches:
      - main
jobs:
  checkout-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: 185.209.179.253
          username: app
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "projetos/Mfs/solicitacao-tryout/back"
          script: "cd /home/app/projetos/Mfs/solicitacao-tryout/back && docker-compose down && docker-compose up -d"
      # - name: Update API
      #   uses: easingthemes/ssh-deploy@main
      #   env:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     key: ${{ secrets.SSH_KEY }}
      #     port: ${{ secrets.SSH_PORT }}
      #     script: cd /home/app/projetos/Mfs/solicitacao-tryout/back && docker-compose down && docker-compose up -d
